version: "3.7"
services:
  mysql-dev:
    image: mysql
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=testdb
    ports:
      - "3600:3306"
  springboot-app:
    build: ./
    expose:
      - "9800"
    ports:
      - 9800:9800
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - mysql-dev