server:
  port: 9800

api:
  url: https://maps.googleapis.com/maps/api/distancematrix/json?
  key: 

spring:
  datasource:
    url       : jdbc:mysql://mysql-dev:3306/testdb
    username  : test
    password  : test
  jpa:
    hibernate:
      ddl-auto: update
